//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Citest.AppConfigModel
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Common;
    using System.Linq;
    using Oracle.DataAccess.Client;

    internal class AdoCommands : IAdoCommands
    {
        public void ExecuteCommand(string request, IEnumerable<object> parameters, DbConnection connection, DbTransaction transaction = null)
        {
            using (new ConnectionHandler(connection))
            {
                using (var command = new OracleCommand(request, (OracleConnection)connection))
                {
                    command.Transaction = (OracleTransaction)transaction;
                    int count = 0;
                    command.Parameters.AddRange(parameters.Select(x => new OracleParameter((count++).ToString(), x)).ToArray());
                    command.ExecuteNonQuery();
                }
            }
        }

        public T ExecuteScalar<T>(string request, IEnumerable<object> parameters, DbConnection connection, DbTransaction transaction = null)
        {
            using (new ConnectionHandler(connection))
            {
                using (var command = new OracleCommand(request, (OracleConnection)connection))
                {
                    command.Transaction = (OracleTransaction)transaction;
                    int count = 0;
                    command.Parameters.AddRange(parameters.Select(x => new OracleParameter((count++).ToString(), x)).ToArray());
                    return (T)command.ExecuteScalar();
                }
            }
        }

        public List<T> ExecuteSelect<T>(string request, IEnumerable<object> parameters, DbConnection connection, DbTransaction transaction = null)
        {
            var func = Material.GetFunc(typeof(T)) as Func<IDataRecord, int, T> ?? ((record, index) => (T)record.GetValue(index));
            return ExecuteSelect<T>(request, parameters, reader => func(reader, 0), connection, transaction);
        }

        public List<T> ExecuteSelect<T>(string request, IEnumerable<object> parameters, Func<IDataReader, T> func, DbConnection connection,DbTransaction transaction = null)
        {
            var output = new List<T>();
            using (new ConnectionHandler(connection))
            {
                using (var command = new OracleCommand(request, (OracleConnection)connection))
                {
                    command.Transaction = (OracleTransaction)transaction;
                    int count = 0;
                    command.Parameters.AddRange(parameters.Select(x => new OracleParameter((count++).ToString(), x)).ToArray());
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            output.Add(func(reader));
                        }
                    }
                }
            }

            return output;
        }
    }
}