//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest.AppConfigModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_LOG
    {
        public decimal LOGID { get; set; }
        public Nullable<decimal> EVENTID { get; set; }
        public decimal PRIORITY { get; set; }
        public string SEVERITY { get; set; }
        public string TITLE { get; set; }
        public System.DateTime TIMESTAMP { get; set; }
        public string MACHINENAME { get; set; }
        public string APPDOMAINNAME { get; set; }
        public string PROCESSID { get; set; }
        public string PROCESSNAME { get; set; }
        public string THREADNAME { get; set; }
        public string WIN32THREADID { get; set; }
        public string FORMATTEDMESSAGE { get; set; }
        public string MESSAGE { get; set; }
    }
}
