//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest.AppConfigModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public string CLIENTONECODE { get; set; }
        public string CONTROL_ID { get; set; }
        public long CLIENT_NUMBER { get; set; }
        public string CLIENT_ID { get; set; }
    }
}
