//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest.AppConfigModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EP_TARGET_INFO
    {
        public decimal INFO_ID { get; set; }
        public string TARGET_CD { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string DATA_TYPE { get; set; }
        public decimal DATA_LENGTH { get; set; }
        public Nullable<decimal> DATA_PRECISION { get; set; }
        public Nullable<decimal> DATA_SCALE { get; set; }
        public string NULLABLE { get; set; }
        public Nullable<short> ENABLED { get; set; }
    }
}
