//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Citest.AppConfigModel
{
    using System.Data;

    public interface IFieldsCaster
    {
        T GetRecord<T>(int index, IDataRecord record);

        T? GetNullableRecord<T>(int index, IDataRecord record) where T : struct;
    }
}