//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Citest.AppConfigModel
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using Oracle.DataAccess.Client;

    public interface IOracleEntity
    {
        void Materialize(IDataRecord input, IFieldsCaster caster);

        string GetOracleInsertRequest(string schemaName);

        string GetOracleUpdateRequest(string schemaName);

        string GetOracleDeleteRequest(string schemaName);

        OracleParameter AddOracleInsertParameters(IEnumerable<IOracleEntity> entities, OracleCommand command);

        void AddOracleUpdateParameters(IEnumerable<IOracleEntity> entities, OracleCommand command);

        void AddOracleDeleteParameters(IEnumerable<IOracleEntity> entities, OracleCommand command);

        void ApplyOutParameter<T>(OracleParameter outParameter, List<T> array) where T : class, IOracleEntity;

        Type[] GetFieldTypes();
    }
}