//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch
    {
        public batch()
        {
            this.chunk = new HashSet<chunk>();
            this.task_item = new HashSet<task_item>();
        }
    
        public System.Guid batch_id { get; set; }
        public int task_type_id { get; set; }
        public string chunk_init_parameters { get; set; }
        public Nullable<int> batch_complete_task_type_id { get; set; }
        public string batch_complete_task_parameters { get; set; }
    
        public virtual task_type task_type { get; set; }
        public virtual task_type task_type1 { get; set; }
        public virtual ICollection<chunk> chunk { get; set; }
        public virtual ICollection<task_item> task_item { get; set; }
    }
}
