//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Citest
{
    using System.Collections.Generic;

    internal class BulkInsertKeysDataReader<T> : BulkInsertDataReader<T> where T : class, IMsSqlEntity
    {
        public BulkInsertKeysDataReader(List<T> entities) : base(entities)
        { }

        public override int FieldCount { get { return Entities[0].GetNumberOfKeyFields(); } }

        public override object GetValue(int i)
        {
            return CurrentEntity.GetKeyValue(i);
        }
    }
}