//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Citest
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Text;

    public partial class chunk : IMsSqlEntity
    {
        public static string SequenceName = "chunk_seq";
        public override bool Equals(object obj)
        {
            return Equals(obj as chunk);
        }

        public bool Equals(chunk other)
        {
            if (other == null)
            {
                return false;
            }

            return chunk_id == other.chunk_id;
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return chunk_id.GetHashCode();
            }
        }

        void IMsSqlEntity.Materialize(IDataRecord input)
        {
            chunk_id = input.GetInt32(0);
            completion_indicator = input[1] as string;
            batch_id = input.GetGuid(2);
        }

        bool IMsSqlEntity.HasIdentity()
        {
            return true;
        }

        int IMsSqlEntity.GetNumberOfFields()
        {
            return 3;
        }

        string IMsSqlEntity.GetTableName()
        {
            return "dbo.chunk";
        }

        string IMsSqlEntity.GetMsSqlInsertRequest()
        {
            return "INSERT INTO dbo.chunk\r\n" +
                "  (completion_indicator, batch_id)\r\n" +
                "OUTPUT inserted.chunk_id\r\n" +
                "VALUES\r\n";
        }

        string IMsSqlEntity.GetMsSqlInsertValues(int i)
        {
            return "(@parm1i" + i + ", @parm2i" + i + ")";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetMsSqlInsertParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, completion_indicator ?? (object)DBNull.Value);
            yield return new SqlParameter("parm2i" + index, batch_id);
        }

        void IMsSqlEntity.PopulateIdentity(IDataRecord input)
        {
            chunk_id = (int)input["chunk_id"];
        }

        object IMsSqlEntity.GetValue(int i)
        {
            switch (i)
            {
                case 0:
                    return chunk_id;
                case 1:
                    return completion_indicator;
                case 2:
                    return batch_id;
            }

            return null;
        }

        string IMsSqlEntity.GetSequenceName()
        {
            return SequenceName;
        }

        void IMsSqlEntity.SetSequence<T>(List<T> list, object seq)
        {
            var sequence = (int)seq;
            list.ForEach(x => (x as chunk).chunk_id = sequence++);
        }

        string IMsSqlEntity.GetUpdateRequest(int index)
        {
            return "UPDATE dbo.chunk\r\n" +
                "SET completion_indicator = @parm1i" + index + ",\r\n" +
                "    batch_id = @parm2i" + index + "\r\n" +
                "WHERE chunk_id = @parm3i" + index + ";";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetUpdateParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, completion_indicator ?? (object)DBNull.Value);
            yield return new SqlParameter("parm2i" + index, batch_id);
            yield return new SqlParameter("parm3i" + index, chunk_id);
        }

        string IMsSqlEntity.GetBulkUpdateRequest(string table)
        {
            return "UPDATE dbo.chunk\r\n" +
                "SET completion_indicator = s.completion_indicator,\r\n" +
                "    batch_id = s.batch_id\r\n" +
                "FROM dbo.chunk tj \r\n" +
                "INNER JOIN " + table + " s\r\n" +
                "ON  tj.chunk_id = s.chunk_id\r\n";
        }

        string IMsSqlEntity.GetCreateTempTableRequest(string table)
        {
            return "CREATE TABLE " + table + "\r\n" +
                "(\r\n" +
                "chunk_id int,\r\n" +
                "completion_indicator char,\r\n" +
                "batch_id uniqueidentifier,\r\n" +
                ")";
        }

        int IMsSqlEntity.GetNumberOfKeyFields()
        {
             return 1;
        }

        string IMsSqlEntity.GetDeleteRequest(int index)
        {
            return "DELETE FROM dbo.chunk\r\n" +
                "WHERE chunk_id = @parm1i" + index + ";";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetDeleteParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, chunk_id);
        }

        string IMsSqlEntity.GetBulkDeleteRequest(string table)
        {
            return "DELETE t FROM dbo.chunk t\r\n" +
                "INNER JOIN " + table + " s\r\n" +
                "ON  t.chunk_id = s.chunk_id\r\n";
        }

        string IMsSqlEntity.GetCreateIdTableRequest(string table)
        {
            return "CREATE TABLE " + table + "\r\n" +
                "(\r\n" +
                "chunk_id int,\r\n" +
                ")";
        }

        object IMsSqlEntity.GetKeyValue(int i)
        {
            switch (i)
            {
                case 0:
                    return chunk_id;
            }

            return null;
        }
    }
}
