//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest
{
    using System;
    using System.Collections.Generic;
    
    public partial class chunk
    {
        public chunk()
        {
            this.task_item_chunk = new HashSet<task_item_chunk>();
        }
    
        public int chunk_id { get; set; }
        public string completion_indicator { get; set; }
        public System.Guid batch_id { get; set; }
    
        public virtual batch batch { get; set; }
        public virtual ICollection<task_item_chunk> task_item_chunk { get; set; }
    }
}
