//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_status
    {
        public int task_status_id { get; set; }
        public int task_id { get; set; }
        public int task_status_type_id { get; set; }
    
        public virtual task task { get; set; }
        public virtual task_status_type task_status_type { get; set; }
    }
}
