//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Citest
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Text;

    public partial class task_status_type : IMsSqlEntity
    {
        public static string SequenceName = "task_status_type_seq";
        public override bool Equals(object obj)
        {
            return Equals(obj as task_status_type);
        }

        public bool Equals(task_status_type other)
        {
            if (other == null)
            {
                return false;
            }

            return task_status_type_id == other.task_status_type_id;
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return task_status_type_id.GetHashCode();
            }
        }

        void IMsSqlEntity.Materialize(IDataRecord input)
        {
            task_status_type_id = input.GetInt32(0);
            status_name = input[1] as string;
        }

        bool IMsSqlEntity.HasIdentity()
        {
            return true;
        }

        int IMsSqlEntity.GetNumberOfFields()
        {
            return 2;
        }

        string IMsSqlEntity.GetTableName()
        {
            return "dbo.task_status_type";
        }

        string IMsSqlEntity.GetMsSqlInsertRequest()
        {
            return "INSERT INTO dbo.task_status_type\r\n" +
                "  (status_name)\r\n" +
                "OUTPUT inserted.task_status_type_id\r\n" +
                "VALUES\r\n";
        }

        string IMsSqlEntity.GetMsSqlInsertValues(int i)
        {
            return "(@parm1i" + i + ")";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetMsSqlInsertParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, status_name ?? (object)DBNull.Value);
        }

        void IMsSqlEntity.PopulateIdentity(IDataRecord input)
        {
            task_status_type_id = (int)input["task_status_type_id"];
        }

        object IMsSqlEntity.GetValue(int i)
        {
            switch (i)
            {
                case 0:
                    return task_status_type_id;
                case 1:
                    return status_name;
            }

            return null;
        }

        string IMsSqlEntity.GetSequenceName()
        {
            return SequenceName;
        }

        void IMsSqlEntity.SetSequence<T>(List<T> list, object seq)
        {
            var sequence = (int)seq;
            list.ForEach(x => (x as task_status_type).task_status_type_id = sequence++);
        }

        string IMsSqlEntity.GetUpdateRequest(int index)
        {
            return "UPDATE dbo.task_status_type\r\n" +
                "SET status_name = @parm1i" + index + "\r\n" +
                "WHERE task_status_type_id = @parm2i" + index + ";";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetUpdateParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, status_name ?? (object)DBNull.Value);
            yield return new SqlParameter("parm2i" + index, task_status_type_id);
        }

        string IMsSqlEntity.GetBulkUpdateRequest(string table)
        {
            return "UPDATE dbo.task_status_type\r\n" +
                "SET status_name = s.status_name\r\n" +
                "FROM dbo.task_status_type tj \r\n" +
                "INNER JOIN " + table + " s\r\n" +
                "ON  tj.task_status_type_id = s.task_status_type_id\r\n";
        }

        string IMsSqlEntity.GetCreateTempTableRequest(string table)
        {
            return "CREATE TABLE " + table + "\r\n" +
                "(\r\n" +
                "task_status_type_id int,\r\n" +
                "status_name nvarchar,\r\n" +
                ")";
        }

        int IMsSqlEntity.GetNumberOfKeyFields()
        {
             return 1;
        }

        string IMsSqlEntity.GetDeleteRequest(int index)
        {
            return "DELETE FROM dbo.task_status_type\r\n" +
                "WHERE task_status_type_id = @parm1i" + index + ";";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetDeleteParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, task_status_type_id);
        }

        string IMsSqlEntity.GetBulkDeleteRequest(string table)
        {
            return "DELETE t FROM dbo.task_status_type t\r\n" +
                "INNER JOIN " + table + " s\r\n" +
                "ON  t.task_status_type_id = s.task_status_type_id\r\n";
        }

        string IMsSqlEntity.GetCreateIdTableRequest(string table)
        {
            return "CREATE TABLE " + table + "\r\n" +
                "(\r\n" +
                "task_status_type_id int,\r\n" +
                ")";
        }

        object IMsSqlEntity.GetKeyValue(int i)
        {
            switch (i)
            {
                case 0:
                    return task_status_type_id;
            }

            return null;
        }
    }
}
