//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public task()
        {
            this.task_status = new HashSet<task_status>();
        }
    
        public int task_id { get; set; }
        public int task_type_id { get; set; }
        public string task_parameters { get; set; }
        public string exclusion_key { get; set; }
    
        public virtual ICollection<task_status> task_status { get; set; }
        public virtual task_type task_type { get; set; }
    }
}
