//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_status_type
    {
        public task_status_type()
        {
            this.task_item_status = new HashSet<task_item_status>();
            this.task_status = new HashSet<task_status>();
        }
    
        public int task_status_type_id { get; set; }
        public string status_name { get; set; }
    
        public virtual ICollection<task_item_status> task_item_status { get; set; }
        public virtual ICollection<task_status> task_status { get; set; }
    }
}
