//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Citest
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Text;

    public partial class task : IMsSqlEntity
    {
        public static string SequenceName = "task_seq";
        public override bool Equals(object obj)
        {
            return Equals(obj as task);
        }

        public bool Equals(task other)
        {
            if (other == null)
            {
                return false;
            }

            return task_id == other.task_id;
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return task_id.GetHashCode();
            }
        }

        void IMsSqlEntity.Materialize(IDataRecord input)
        {
            task_id = input.GetInt32(0);
            task_type_id = input.GetInt32(1);
            task_parameters = input[2] as string;
            exclusion_key = input[3] as string;
        }

        bool IMsSqlEntity.HasIdentity()
        {
            return true;
        }

        int IMsSqlEntity.GetNumberOfFields()
        {
            return 4;
        }

        string IMsSqlEntity.GetTableName()
        {
            return "dbo.task";
        }

        string IMsSqlEntity.GetMsSqlInsertRequest()
        {
            return "INSERT INTO dbo.task\r\n" +
                "  (task_type_id, task_parameters, exclusion_key)\r\n" +
                "OUTPUT inserted.task_id\r\n" +
                "VALUES\r\n";
        }

        string IMsSqlEntity.GetMsSqlInsertValues(int i)
        {
            return "(@parm1i" + i + ", @parm2i" + i + ", @parm3i" + i + ")";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetMsSqlInsertParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, task_type_id);
            yield return new SqlParameter("parm2i" + index, task_parameters ?? (object)DBNull.Value);
            yield return new SqlParameter("parm3i" + index, exclusion_key ?? (object)DBNull.Value);
        }

        void IMsSqlEntity.PopulateIdentity(IDataRecord input)
        {
            task_id = (int)input["task_id"];
        }

        object IMsSqlEntity.GetValue(int i)
        {
            switch (i)
            {
                case 0:
                    return task_id;
                case 1:
                    return task_type_id;
                case 2:
                    return task_parameters;
                case 3:
                    return exclusion_key;
            }

            return null;
        }

        string IMsSqlEntity.GetSequenceName()
        {
            return SequenceName;
        }

        void IMsSqlEntity.SetSequence<T>(List<T> list, object seq)
        {
            var sequence = (int)seq;
            list.ForEach(x => (x as task).task_id = sequence++);
        }

        string IMsSqlEntity.GetUpdateRequest(int index)
        {
            return "UPDATE dbo.task\r\n" +
                "SET task_type_id = @parm1i" + index + ",\r\n" +
                "    task_parameters = @parm2i" + index + ",\r\n" +
                "    exclusion_key = @parm3i" + index + "\r\n" +
                "WHERE task_id = @parm4i" + index + ";";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetUpdateParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, task_type_id);
            yield return new SqlParameter("parm2i" + index, task_parameters ?? (object)DBNull.Value);
            yield return new SqlParameter("parm3i" + index, exclusion_key ?? (object)DBNull.Value);
            yield return new SqlParameter("parm4i" + index, task_id);
        }

        string IMsSqlEntity.GetBulkUpdateRequest(string table)
        {
            return "UPDATE dbo.task\r\n" +
                "SET task_type_id = s.task_type_id,\r\n" +
                "    task_parameters = s.task_parameters,\r\n" +
                "    exclusion_key = s.exclusion_key\r\n" +
                "FROM dbo.task tj \r\n" +
                "INNER JOIN " + table + " s\r\n" +
                "ON  tj.task_id = s.task_id\r\n";
        }

        string IMsSqlEntity.GetCreateTempTableRequest(string table)
        {
            return "CREATE TABLE " + table + "\r\n" +
                "(\r\n" +
                "task_id int,\r\n" +
                "task_type_id int,\r\n" +
                "task_parameters nvarchar(max),\r\n" +
                "exclusion_key nvarchar,\r\n" +
                ")";
        }

        int IMsSqlEntity.GetNumberOfKeyFields()
        {
             return 1;
        }

        string IMsSqlEntity.GetDeleteRequest(int index)
        {
            return "DELETE FROM dbo.task\r\n" +
                "WHERE task_id = @parm1i" + index + ";";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetDeleteParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, task_id);
        }

        string IMsSqlEntity.GetBulkDeleteRequest(string table)
        {
            return "DELETE t FROM dbo.task t\r\n" +
                "INNER JOIN " + table + " s\r\n" +
                "ON  t.task_id = s.task_id\r\n";
        }

        string IMsSqlEntity.GetCreateIdTableRequest(string table)
        {
            return "CREATE TABLE " + table + "\r\n" +
                "(\r\n" +
                "task_id int,\r\n" +
                ")";
        }

        object IMsSqlEntity.GetKeyValue(int i)
        {
            switch (i)
            {
                case 0:
                    return task_id;
            }

            return null;
        }
    }
}
