//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_type
    {
        public task_type()
        {
            this.batch = new HashSet<batch>();
            this.batch1 = new HashSet<batch>();
            this.task = new HashSet<task>();
        }
    
        public int task_type_id { get; set; }
        public string task_name { get; set; }
        public string assembly_location { get; set; }
        public string class_name { get; set; }
    
        public virtual ICollection<batch> batch { get; set; }
        public virtual ICollection<batch> batch1 { get; set; }
        public virtual ICollection<task> task { get; set; }
    }
}
