//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_item_chunk
    {
        public int chunk_id { get; set; }
        public int task_item_id { get; set; }
        public Nullable<bool> dummy { get; set; }
    
        public virtual chunk chunk { get; set; }
        public virtual task_item task_item { get; set; }
    }
}
