//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Citest
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Text;

    public partial class task_item_status : IMsSqlEntity
    {
        public static string SequenceName = "task_item_status_seq";
        public override bool Equals(object obj)
        {
            return Equals(obj as task_item_status);
        }

        public bool Equals(task_item_status other)
        {
            if (other == null)
            {
                return false;
            }

            return task_item_status_id == other.task_item_status_id;
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return task_item_status_id.GetHashCode();
            }
        }

        void IMsSqlEntity.Materialize(IDataRecord input)
        {
            task_item_status_id = input.GetInt32(0);
            task_item_id = input.GetInt32(1);
            task_status_type_id = input.GetInt32(2);
        }

        bool IMsSqlEntity.HasIdentity()
        {
            return true;
        }

        int IMsSqlEntity.GetNumberOfFields()
        {
            return 3;
        }

        string IMsSqlEntity.GetTableName()
        {
            return "dbo.task_item_status";
        }

        string IMsSqlEntity.GetMsSqlInsertRequest()
        {
            return "INSERT INTO dbo.task_item_status\r\n" +
                "  (task_item_id, task_status_type_id)\r\n" +
                "OUTPUT inserted.task_item_status_id\r\n" +
                "VALUES\r\n";
        }

        string IMsSqlEntity.GetMsSqlInsertValues(int i)
        {
            return "(@parm1i" + i + ", @parm2i" + i + ")";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetMsSqlInsertParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, task_item_id);
            yield return new SqlParameter("parm2i" + index, task_status_type_id);
        }

        void IMsSqlEntity.PopulateIdentity(IDataRecord input)
        {
            task_item_status_id = (int)input["task_item_status_id"];
        }

        object IMsSqlEntity.GetValue(int i)
        {
            switch (i)
            {
                case 0:
                    return task_item_status_id;
                case 1:
                    return task_item_id;
                case 2:
                    return task_status_type_id;
            }

            return null;
        }

        string IMsSqlEntity.GetSequenceName()
        {
            return SequenceName;
        }

        void IMsSqlEntity.SetSequence<T>(List<T> list, object seq)
        {
            var sequence = (int)seq;
            list.ForEach(x => (x as task_item_status).task_item_status_id = sequence++);
        }

        string IMsSqlEntity.GetUpdateRequest(int index)
        {
            return "UPDATE dbo.task_item_status\r\n" +
                "SET task_item_id = @parm1i" + index + ",\r\n" +
                "    task_status_type_id = @parm2i" + index + "\r\n" +
                "WHERE task_item_status_id = @parm3i" + index + ";";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetUpdateParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, task_item_id);
            yield return new SqlParameter("parm2i" + index, task_status_type_id);
            yield return new SqlParameter("parm3i" + index, task_item_status_id);
        }

        string IMsSqlEntity.GetBulkUpdateRequest(string table)
        {
            return "UPDATE dbo.task_item_status\r\n" +
                "SET task_item_id = s.task_item_id,\r\n" +
                "    task_status_type_id = s.task_status_type_id\r\n" +
                "FROM dbo.task_item_status tj \r\n" +
                "INNER JOIN " + table + " s\r\n" +
                "ON  tj.task_item_status_id = s.task_item_status_id\r\n";
        }

        string IMsSqlEntity.GetCreateTempTableRequest(string table)
        {
            return "CREATE TABLE " + table + "\r\n" +
                "(\r\n" +
                "task_item_status_id int,\r\n" +
                "task_item_id int,\r\n" +
                "task_status_type_id int,\r\n" +
                ")";
        }

        int IMsSqlEntity.GetNumberOfKeyFields()
        {
             return 1;
        }

        string IMsSqlEntity.GetDeleteRequest(int index)
        {
            return "DELETE FROM dbo.task_item_status\r\n" +
                "WHERE task_item_status_id = @parm1i" + index + ";";
        }

        IEnumerable<SqlParameter> IMsSqlEntity.GetDeleteParameters(int index)
        {
            yield return new SqlParameter("parm1i" + index, task_item_status_id);
        }

        string IMsSqlEntity.GetBulkDeleteRequest(string table)
        {
            return "DELETE t FROM dbo.task_item_status t\r\n" +
                "INNER JOIN " + table + " s\r\n" +
                "ON  t.task_item_status_id = s.task_item_status_id\r\n";
        }

        string IMsSqlEntity.GetCreateIdTableRequest(string table)
        {
            return "CREATE TABLE " + table + "\r\n" +
                "(\r\n" +
                "task_item_status_id int,\r\n" +
                ")";
        }

        object IMsSqlEntity.GetKeyValue(int i)
        {
            switch (i)
            {
                case 0:
                    return task_item_status_id;
            }

            return null;
        }
    }
}
