//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskTrackerEntities : DbContext
    {
        public TaskTrackerEntities()
            : base("name=TaskTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch> batch { get; set; }
        public virtual DbSet<chunk> chunk { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<task_item> task_item { get; set; }
        public virtual DbSet<task_item_chunk> task_item_chunk { get; set; }
        public virtual DbSet<task_item_status> task_item_status { get; set; }
        public virtual DbSet<task_status> task_status { get; set; }
        public virtual DbSet<task_status_type> task_status_type { get; set; }
        public virtual DbSet<task_type> task_type { get; set; }
    }
}
